### ISSUE TITLE
[feature request] Integration with JOBS+ mod

### ISSUE THREAD

**Issue by jinkhya** [Lightman314/Lightmans-Discord-Integration#10]
Hello, 
This is a feature request for compatibility with [Jobs+ mod](https://github.com/DAQEM/JobsPlus). That mod adds a prefix to names in chat (if the player enables it) and it gets quite messy with Discord relay 😅 . I dunno how much work this represents nor if you're interested but it'd be really cool to have some kind of formatting that doesn't have all the color codes but something simpler like bold or brackets or something.
Here's what it looks like in game :
![image](https://user-images.githubusercontent.com/10158963/199932444-54672293-a7fd-45ac-9872-155492cba592.png)
and in discord : (I had hunter on the server, and hunter in sp but idea is the same)
![image](https://user-images.githubusercontent.com/10158963/199932642-f38f61e2-35cb-460e-a81b-ecc162820f56.png)

If you need any other kind of information let me know!
Thanks,
Jin

**Comment by Lightman314** [comment]
Considering that it already adds the prefix appropriately (albeit with the style codes included), it would seem that all I should need to do is clear out said style codes... Which shouldn't be too hard to do, so I'll see if I can get my code to remove those for discord messages

**Comment by jinkhya** [comment]
awesome :D

**Comment by Lightman314** [comment]
Should now properly clear the formatting codes on v0.1.0.0.
