### ISSUE TITLE
Crash with JustEnoughAdvancements (JEA) - 1.16.5 Forge Server

### ISSUE THREAD

**Issue by Foxydapirate12** [Lightman314/Lightmans-Discord-Integration#14]
This is with the latest version of Forge, Lightmans Discord, JEA, and Libx. Here's the crash report: https://mclo.gs/NgxBs1z
Specific Version Numbers:
Forge: 1.16.5-36.2.39
LMDI: 1.16.4-0.0.3.1
JEA: 1.16.5-1.0.2
LibX: 1.16.3-1.0.76
Also here's the log: https://mclo.gs/wWjpAAk

Also Long time, no speak!!

Edit: Ok, so i've just done a bit of testing and it seems to be specifically LibX that is causing the crash with LMDI, Here's the Latest.log: https://mclo.gs/jFUuHlQ

**Comment by Lightman314** [comment]
LDI 1.16 is no longer supported and will not receive any updates in the future.
