### ISSUE TITLE
Some characters are not properly displayed on discord

### ISSUE THREAD

**Issue by HollishKid** [Lightman314/Lightmans-Discord-Integration#15]
As I changed some of the strings in `lightmansdiscord_messages.txt`, I noticed that some characters are not displayed properly on discord. Namely, they are characters with accents (é, ê, etc.).
Is this a mistake on my behalf or is there something that you can do?

Forge: 1.16.5-36.2.39
LMDI: 1.16.4-0.0.3.1

**Comment by Lightman314** [comment]
This has been fixed in future versions, however this will not be fixed for LDI 1.16 as it is no longer supported.
