### ISSUE TITLE
Crash from items/entity renders and such

### ISSUE THREAD

**Issue by chrislightsaber** [Lightman314/Lightmans-Discord-Integration#16]
Light blue and gray trader as well as slot machine crash my game.
[crash-2023-07-11_14.36.58-client.txt](https://github.com/Lightman314/Lightmans-Discord-Integration/files/12018555/crash-2023-07-11_14.36.58-client.txt)
[crash-2023-07-11_14.39.59-client.txt](https://github.com/Lightman314/Lightmans-Discord-Integration/files/12018556/crash-2023-07-11_14.39.59-client.txt)
[crash-2023-07-11_14.42.42-client.txt](https://github.com/Lightman314/Lightmans-Discord-Integration/files/12018557/crash-2023-07-11_14.42.42-client.txt)
[crash-2023-07-11_14.44.00-client.txt](https://github.com/Lightman314/Lightmans-Discord-Integration/files/12018558/crash-2023-07-11_14.44.00-client.txt)

**Comment by chrislightsaber** [comment]
1.20.1a Crashes when getting the blocks or placing them

**Comment by Lightman314** [comment]
Your issue is noted, and will be fixed.

I will note, however, that this is the issue report section for Lightman's Discord Integration, not for Lightman's Currency, and thus this issue is not valid for where it was reported.
