### ISSUE TITLE
Request Banker Mob/NPC

### ISSUE THREAD

**Issue by jasons49** [Lightman314/Lightmans-Discord-Integration#21]
I wanted to ask you if there was anyway you could add a mob like a villager that acts like a banker (maybe make it a village profession) that a player could interact with to access their bank accounts like the atm? Preferrably for 1.18.2

(Deepest apologies for mistakes with realizing what you mean by github)
Really sorry

**Comment by Lightman314** [comment]
This is the Lightman's Discord Integration github page, not the Lightman's Currency page.

Please post this here: https://github.com/Lightman314/LightmansCurrency/issues
