### ISSUE TITLE
Formatting issue when using SMP Essentials mod

### ISSUE THREAD

**Issue by ItsPandAce** [Lightman314/Lightmans-Discord-Integration#22]
When using the Lightmans Discord Integration mod with the SMP Essentials mod there are some formatting issues.

![image](https://github.com/Lightman314/Lightmans-Discord-Integration/assets/133909461/c30e40b6-41d6-4449-b621-2e9a7f49b31b)

Among other things the SMP Essentials mod modifies the nametag of the player giving it a certain color and it can add a team name to it. The formatting of the player's nametag is then displayed in discord.

Would you be able to take a look at this and see if you could prevent the formatting from displaying in discord?

I'm using the following versions:
- lightmansdiscord-1.18-0.2.0.2-server.jar
- kotlinforforge-3.12.0-all.jar
- smpessentials-1.18.2-1.0.jar
- Forge -> 1.18.2 - 40.2.5

SMP Essentials mod: https://www.curseforge.com/minecraft/mc-mods/smpessentials/files/4726864

**Comment by Lightman314** [comment]
I think I see the issue. I added a filter to remove the formatting codes from the players names, but it's only getting applied to the chat messages specifically, instead of all messages (which is why they appear in the join/leave messages, but not the actual chat message).

**Comment by ItsPandAce** [comment]
Thank you for checking it out so quickly. So does this mean you'll be able to fix it?

**Comment by Lightman314** [comment]
Aye. I'll try to get a fix out later today.

**Comment by Lightman314** [comment]
Should be fixed in v0.2.0.3. Hopefully curseforge approves the files in a timely manner this time...

**Comment by ItsPandAce** [comment]
I tested the version on modrinth and it works perfectly. Thank you so much for fixing so quickly <3
