### ISSUE TITLE
Suggestion concerning the server compatibility message

### ISSUE THREAD

**Issue by RavanCraft** [Lightman314/Lightmans-Discord-Integration#4]
After I added Lightmans-Discord-Integration the server shows "Incompatible FML modded Server - Server has additional mods that may be needed on the client". 

As I don't see that for other sever side only mods, I assume there must be a way to tell the pack, that this mod is not leading to incompatibility.

Would be wonderful if this could be integrated. Thank you!

**Comment by Lightman314** [comment]
If you can give me an example of one of the server side mods that doesn't have this issue (ideally an open-source one), I'd be happy to look into it. Unfortunately any time I try to google a solution to this issue, the results are always for older forge versions and don't work on 1.16/1.18.

**Comment by Lightman314** [comment]
Figured it out. Fixed in v0.0.3.5

**Comment by RavanCraft** [comment]
Wow, that is awesome! I'll check it out! Thank you!
