### ISSUE TITLE
Question: Is there an option to have server messages send to the Discord?

### ISSUE THREAD

**Issue by RavanCraft** [Lightman314/Lightmans-Discord-Integration#5]
I have for example a warning message that the server will shut down in a few minutes which is send by the server. Unfortunately this is not send to my Discord channel. It would be very helpful for people to see messages like this in Discord as well.

**Comment by Lightman314** [comment]
At the moment there isn't any way of doing that, but if I knew what methods you're using to send the message I could probably look into it.

**Comment by RavanCraft** [comment]
Ok, I'll try to find out. Thank you for the feedback!

**Comment by VirtualGaming1** [comment]
I would like to +1 this

I just on the server's scheduler and this is type of command I have it sent.

this is for count down
/title @a title {"text":"3","bold":true}

and the just a message
/tellraw @a {"text":"Server will restart in 1 hour"}

**Comment by Lightman314** [comment]
Question: Would simply adding a command that sends a message to discord & only discord work?

i.e. Adding a command that upon receiving
`/telldiscord Server will restart in 1 hour!`
will post a message in the discord #server-chat channel saying `Server will restart in 1 hour!`

Then you could probably set up your scheduler systems to run the /telldiscord command at the same time as it sends the /tellraw & /title messages.

I feel like this would be the best solution personally, as some people may not want the bot to be listening in to their /title & /tellraw messages, as some may be used for single-target messages that they don't want posted to the general public.

**Comment by VirtualGaming1** [comment]
> Question: Would simply adding a command that sends a message to discord & only discord work?
> 
> i.e. Adding a command that upon receiving `/telldiscord Server will restart in 1 hour!` will post a message in the discord #server-chat channel saying `Server will restart in 1 hour!`
> 
> Then you could probably set up your scheduler systems to run the /telldiscord command at the same time as it sends the /tellraw & /title messages.
> 
> I feel like this would be the best solution personally, as some people may not want the bot to be listening in to their /title & /tellraw messages, as some may be used for single-target messages that they don't want posted to the general public.

I am down for that one.

**Comment by Lightman314** [comment]
Cool, that should be easy enough to add, so I'll see if I can get that done sometime tomorrow.

**Comment by Lightman314** [comment]
'/telldiscord \<message>' command has been added in v0.0.3.8.

**Comment by VirtualGaming1** [comment]
nice I will test it on my close beta server as i just updated it last night
